language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-22
sudo: required
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean build --continue

